full_path: "/mnt/f/asmapp/"
assembly: "Msporidia"  # name of starting assembly, located in data/aassemblies/
reads: "Msporidia_reads"   # name of reads, located in data/reads/
# memory: "30"  # the available memory for the analysis in gigabytes
threads: "8"
ncbi_nt_path: "/mnt/f/databases/blast/"
seq_tech: "pb"
reference: "data/assemblies/Msporidia"
mitochondrial: "data/assemblies/mito"
ploidy: "1"