full_path: "/media/mike/WD_4TB/karyon_longread/"
assembly: "VW4_HiFiasm.15.p_ctg.purge.SLR"  # name of starting assembly, located in data/aassemblies/
reads: "all_hifi"   # name of reads, located in data/reads/
redundans_path: "/home/mike/software/redundans"  # path to directory containing redundans script
picard-tools: "/home/mike/software/picard/"  # path to picard-tools
memory: "40"  # the available memory for the analysis in gigabytes
threads: "12"
quast_path: "/home/mike/software/quast"
seq_tech: "hifi"
reference: "data/assemblies/Blanc_Mathieu_2017_mJavanica"
