full_path: "/mnt/f/asmapp/"
assembly: "Msporidia"  # name of starting assembly, located in data/assemblies/
reads: "Msproridia_reads"   # name of reads, located in data/reads/
# memory: "30"  # the available memory for the analysis in gigabytes
threads: "4"
quast_path: "~/software/quast"  # possibly redundant
ncbi_nt_path: "/mnt/f/databases/ncbi_db/nt"
seq_tech: "hifi"
reference: "Msporidia"
mitochondrial: "mito"
ploidy: "4"
