full_path: ""
assembly: ""  # name of starting assembly, located in data/aassemblies/
reads: ""   # name of reads, located in data/reads/
redundans_path: ""  # path to directory containing redundans script
memory: ""  # the available memory for the analysis in gigabytes
threads: ""
quast_path: ""
ncbi_nt_path: ""
seq_tech: ""
reference: ""
