assembly: "VW4_CANU_HiFi"  # name of starting assembly, located in data/aassemblies/
reads: "VW4_CANU_HiFi.trimmedReads"   # name of reads, located in data/reads/
redundans_path: "/home/531734/packages/redundans"  # path to directory containing redundans script
picard-tools: "/home/"  # path to picarad-tools
memory: "120"  # the aavailaable memory for the analysis in gigabytes
threads: "28"
quast_path: "/home/531734/packages/quast"
seq_tech: "hifi"
reference: "data/assemblies/Blanc_Mathieu_2017_mJavanica"
