site_name: ASMAPP
site_url: https://ASMAPP.com/
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Installation': 'user-guide/installation.md'
        - 'Quick start': 'user-guide/quick-start.md'
        - 'Configuration': 'user-guide/configuration.md'
        - 'Use cases': 'user-guide/use-cases.md'
    - About:
        - 'License': 'license.md'
        - 'References': 'references.md'